<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\tModLoader.targets" />

	<PropertyGroup>

	</PropertyGroup>
	
	<ItemGroup>

		<Reference Include="FargowiltasSouls">
			<HintPath>..\ModAssemblies\FargowiltasSouls_v1.7.2.14.dll</HintPath>
		</Reference>

		<Reference Include="Fargowiltas">
			<HintPath>..\ModAssemblies\Fargowiltas_v3.3.6.3.dll</HintPath>
		</Reference>

		<Reference Include="Luminance">
			<HintPath>..\ModAssemblies\Luminance_v1.0.12.dll</HintPath>
		</Reference>

		<Reference Include="CalamityMod">
			<HintPath>..\ModAssemblies\CalamityMod_v2.0.5.dll</HintPath>
		</Reference>

		<Reference Include="InfernumMode">
			<HintPath>..\ModAssemblies\InfernumMode_v2.0.1.19.dll</HintPath>
		</Reference>

		<Reference Include="FargowiltasCrossmod">
			<HintPath>..\ModAssemblies\FargowiltasCrossmod_v1.2.0.16.dll</HintPath>
		</Reference>

		<Reference Include="ssm">
			<HintPath>..\ModAssemblies\ssm_v1.1.4.2.dll</HintPath>
		</Reference>

		<Reference Include="CalamityModMusic">
			<HintPath>..\ModAssemblies\CalamityModMusic_v2.0.5.dll</HintPath>
		</Reference>
		
	</ItemGroup>

</Project>